apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-sample-ingress
spec:
  ingressClassName: ingress-internal
  rules:
  - host: ce-82263854-sa.kubepia.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: cloud-sample
            port:
              name: http
        pathType: Prefix