apiVersion : apps/v1
kind: Deployment
metadata:
  name: "82263854" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "82263854"
  template:
    metadata:
      labels:
        app: "82263854" 
    spec:
      containers:
        - name: "82263854" 
          image: ce82263854acr.azurecr.io/82263854
          ports:
          - containerPort: 8080
